publishDir = "_build"
baseURL = "https://tomasfiers.net/"
languageCode = "en-us"
title = "Tomas Fiers"
theme = "hyde"

# Enable << ```python [some code]``` >> syntax in markdown
pygmentsCodeFences = true
