[Settings]
  ID = "tomasfiers.net"

[build]
  # Static site generator (.md > .html)
  command = "hugo"
  # Directory to save the html to
  publish = "_build/"

[context.production.environment]
  HUGO_VERSION = "0.42"
